version: "2"
services:
    proxy:
        image: httpd
        depends_on:
          - node
    node:
        image: node:alpine
        ports:
          - 3000:3000
        depends_on:
          - redis
    redis:
        image: redis
        ports:
          - "6379:6379"
        volumes:
          - ../data/redis:/data
        entrypoint: redis-server --appendonly yes
        restart: always