version: "2"
services:
    haproxy:
        image: haproxy:1.8-alpine
        port: 
          - "80:8081"
        depends:
          - windows
    windows:
        image: microsoft/iis
        depends:
          - redis
          - elastic
          - sqlserver
    sqlserver:
        image: microsoft/mssql-server-linux
        ports:
          - "1433:1433"
        environment:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: stackOverflowPassword
        restart: always
    elastic:
        image: elasticsearch:5.6.13-alpine
        ports: 
          - "9200:9200"
    redis:
        image: redis
        ports:
          - "6379:6379"
        volumes:
          - ../data/redis:/data
        entrypoint: redis-server --appendonly yes
        restart: always